### PR TITLE
Fix template regex in Scenario Outline expansion (#161)

### LINKED ISSUE #161: Fail to parse feature when template are touching each other
## Context

Given the following scenario

```gherkin
Feature: Test touching template
  Scenario Outline: test template
    Given The name <Left><Right>
    Then The name is <Full>

    Examples:
      | Left | Right | Full   |
      | Foo  | Bar   | FooBar |
```

I'm getting the following error

```
Failed to parse: Failed to expand examples: Failed to resolve <Left><Right>
```

The error is present on the following version:
- ab430cc (current `main` at the time)
- `0.10.2`

## How to replicate

```sh
git clone --depth 1 git@github.com:cucumber-rs/cucumber.git
cd cucumber
cat << EOF | tee tests/features/wait/template.feature
Feature: Test touching template
  Scenario Outline: test template
    Given The name <Left><Right>
    Then The name is <Full>

    Examples:
      | Left | Right | Full   |
      | Foo  | Bar   | FooBar |
EOF
cargo test
```

## What I'm expecting

I'm expecting the Feature to be correctly parsed

### PR DESCRIPTION
**Pull request by ilslv**
Resolves #161

## Synopsis

See #161 for context.

## Solution

Change `TEMPLATE_REGEX` from `<(\S+)>` to `<([^>\s]+)>`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
## FCM

```
Fix template regex in Scenario Outline expansion (#163, #161) 
```

File: src/feature.rs [hunk 1]
```diff
@@ -126,7 +126,7 @@ fn expand_scenario(
     /// [`Examples`]: gherkin::Examples
     #[allow(clippy::expect_used)]
     static TEMPLATE_REGEX: Lazy<Regex> =
-        Lazy::new(|| Regex::new(r"<(\S+)>").expect("incorrect Regex"));
+        Lazy::new(|| Regex::new(r"<([^>]+)>").expect("incorrect Regex"));
```
Comment (tyranron) [inline src/feature.rs]: But we allow `[ \t\r\n\f]` now, which doesn't seem to be good. I think `[^>\s]` is better here.

**Review by tyranron — APPROVED** [review]
