### PR TITLE
Pass the `World` to after hook even if `Step` has failed (#207)

### LINKED ISSUE #207: After hook is odd to work with
I'm attempting to convert some of our automated testing to use `cucumber-rs`, but I'm finding it hard to tear down my tests.

If the last step fails, the `after` hook doesn't provide a `World` to work with. I need the `World` to get to its state and make decisions on tear down.

My `after` hook:

```rust
#[tokio::main]
async fn main() {
    BalloonWorld::cucumber()
        .max_concurrent_scenarios(1)
        .after(|_, _, _, maybe_world| {
            println!("AFTER! {:?}", maybe_world);
            Box::pin(async move {
                println!("AFTER IN FUT {:?}", maybe_world);
            })
        })
        .run_and_exit("features")
        .await;
}
```

image

What's the recommended way to make this work?

Basically we're creating Fly.io apps and then we need to make sure they are tore down, whatever the outcome of the tests.

### PR DESCRIPTION
**Pull request by ilslv**
Resolves #207

## Synopsis

For now `after` hook accepts mutable reference to the `World` instance, but only in case `Step` didn't fail.

## Solution

Accept shared reference to the `World` instance (it's ok because it's not passed on either way) and pass it even in case  `Step` has failed.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
## FCM

```
Pass the `World` to `after` hook even if `Step` has failed (#209, #207)

- receive shared reference to the `World` in `after` hook callback
```

**Review by tyranron — CHANGES_REQUESTED** [review]
Discussed to preserve `&mut World` in After Hook.

**Comment by ilslv** [comment]
I've left changes in `0.13` release inside `CHANGELOG.md`, because despite stability of the API, behaviour of `Hook::After` have changed and theoretically can break user code (for example assertions about number of passed/failed hooks), but I'm not sure about this decision. [semver](https://semver.org) doesn't specify what to do in this case.

**Comment by tyranron** [comment]
@ilslv I'd opt for going with patch release for that.

File: src/runner/basic.rs [hunk 1]
```diff
@@ -1053,16 +1056,151 @@ where
...
+        scenario: Arc<gherkin::Scenario>,
+        world: Option<Arc<W>>,
+        err: Option<Info>,
+    ) {
+        if self.after_hook.is_some() {
+            // TODO: This `Hook::Started` event is emitted after
+            //       `HookType::After` is executed, so it can slightly mess up
+            //       timing if `timestamps` feature is enabled. Fix it by
+            //       passing here `event::Metadata` at the time
+            //       `HookType::After` was started.
```
Comment (tyranron) [inline src/runner/basic.rs:1122]: @ilslv I don't see why we should postpone this. Please, fix in a separate PR.

**Review by tyranron — APPROVED** [review]
