### PR TITLE
Retry failed `Scenario`s (#212)

### LINKED ISSUE #212: Replay failed tests
I was wondering if it's something that we can add to the framework. We already have a function to repeat failed tests output but we don't have a function to run failed tests again. It's common to have flaky tests that sometimes can be solved by running them again.

For example : 

```
#[tokio::main]
async fn main() {
    AnimalWorld::cucumber()
        .replay_failed(2)
        .run_and_exit("tests/features/book/output/terminal_repeat_failed.feature")
        .await;
}
```

Where 2 is the maximum number of times the tests should be run again in case of test failures. Let's say we have the tests `A`, `B`, `C` and `D` :

1. During the first run only `A` passes
2. Then `B`, `C` and `D` are run again (1 replay left if we have new test failures)
3. Only B passes, we run again `C` and `D` (0 replay left)
4. `D` fails again, this one is certainly more than just unstable

Regarding the output we have two choices :

- Print all test executions : it's transparent but can be repetitive when the tests fail multiple times (like `D` in this example)
- Or just print the result once the last replay is done (which can be the maximum, here `2`, or a previous run if all tests are passing)

### PR DESCRIPTION
**Pull request by ilslv**
Resolves #212   
Superseeds #214

## Synopsis

For now there is no way to retry failed `Scenario`s. 

## Solution

Implement ability to implement retries of failed `Scenario`s with:
1. Tags `@retry`/`@retry(3)`/`@retry.after(3s)`/`@retry(5).after(all)`
2. CLI options `--retry=3`/`--retry-after=30ms`/`--retry-after=all`

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests
[format]: https://github.com/rust-lang/rust/issues/49359

### CODE REVIEW

**Comment by ilslv** [comment]
## FCM

```
Retry failed `Scenario`s (#223, #212)
```

File: src/runner/basic.rs [hunk 1]
```diff
@@ -121,6 +272,7 @@ type Failed = bool;
 pub struct Basic<
     World,
     F = WhichScenarioFn,
+    R = RetryOptionsFn,
```
Comment (tyranron) [inline src/runner/basic.rs:275]: @ilslv maybe we could just `Box<dyn FnMut>` here instead of introducing yet another type parameter? Doesn't seem to be critical.

File: src/runner/basic.rs [hunk 2]
```diff
@@ -198,18 +374,61 @@ impl<World> Default for Basic<World> {
...
+                                    num.parse::<usize>()
+                                        .ok()
+                                        .map(|num| (Some(num), rest))
+                                })
+                            })
+                            .unwrap_or((None, retries));
+
+                        let at =
+                            rest.strip_prefix(".after").and_then(|after| {
+                                after.strip_prefix('(').and_then(|after| {
```
Comment (tyranron) [inline src/runner/basic.rs:395]: @ilslv would be nice to refactor tags parsing into a separate function on `RetryOptions`, and so cover it with unit tests.

**Review by tyranron — CHANGES_REQUESTED** [review]

**Review by tyranron — APPROVED** [review]
