### PR TITLE
Fix `fail_on_skipped` for `Background` steps

### LINKED ISSUE #198: Fail background skipped tests
Currently, running a test with `fail_on_skipped()` does not fail `Background` skipped tests. The reason is because the `Background` steps are not being mapped as the steps directly under the `Scenario` are:
https://github.com/cucumber-rs/cucumber/blob/935602b2cb36be7466f96af14315fe7db03e0f84/src/writer/fail_on_skipped.rs#L92-L95
#
If that was the only thing that needed to be changed, it would be easy (_spoiler: it is not_); all it takes is to copy code above and replace `Scenario::Step` with `Scenario::Background`.
```rust
Cucumber::Feature(
    f,
    Feature::Scenario(sc, Scenario::Background(st, Step::Skipped)),
) => map_failed(f, None, sc, st),
```

It does work, but it also leads to another issue. Once we force skipped background steps to fail, we should also allow the usage of `@allow.skipped` on these steps, which is not possible because, [as you clearly stated](https://cucumber-rs.github.io/cucumber/current/writing/tags.html#failing-on-skipped-steps), we cannot use tags above `Background`.

I know you guys went deep redesigning this, so I want to understand your reasoning before proposing anything or making changes locally. My questions are:
- To fail skipped `Background` tests is not available _by design_?
- What is the reason for not allowing tags above `Background`? 

Thank you!

### PR DESCRIPTION
**Pull request by rogertorres**
Resolve #198 by including `Background` steps into the function that converts `Skipped` steps into `Failed` ones.

### CODE REVIEW

File: src/writer/fail_on_skipped.rs [hunk 1]
```diff
@@ -86,17 +95,24 @@ where
                     f,
                     Feature::Rule(
                         r,
-                        Rule::Scenario(sc, Scenario::Step(st, Step::Skipped)),
+                        Rule::Scenario(sc, Scenario::Background(st, Step::Skipped)),
                     ),
-                ) => map_failed(f, Some(r), sc, st),
+                ) => map_failed_bg(f, Some(r), sc, st),
```
Comment (ilslv) [inline src/writer/fail_on_skipped.rs:103]: Actually, we want to map our failed `Background` `Step`s into `event::Scenario::Background`, not into `event::Scenario::Step` like with regular `Step`s

**Comment by ilslv** [comment]
## FCM

```
Skipped `Background` steps not failing with `writer::FailOnSkipped` (#199, #198)
```

**Review by tyranron — APPROVED** [review]
@rogertorres thanks! 🍻
